services:
  - type: web
    name: leet2git-api
    env: python
    buildCommand: pip install uv && uv sync
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port 
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: ENCRYPTION_SALT
        sync: false